replaces minutes.file in service now instead of in frontend
kanselarij-vlaanderen/minutes-report-generation-service pull request #3
Opened 2023-09-27 09:39 UTC by StuyckRuben

https://kanselarij.atlassian.net/browse/KAS-4293

2023-10-10 09:37 UTC, sergiofenoll requested changes

2023-10-10 09:37 UTC, sergiofenoll commented on app.ts
> +    ?minutes dct:modified ${sparqlEscapeDate(new Date())}
**issue**: remove the old modified date if you insert a new one

2023-10-10 09:37 UTC, sergiofenoll commented on app.ts
> +    ?minutes dct:modified ${sparqlEscapeDate(new Date())}
**chore**: use `sparqlEscapeDateTime`

2023-10-20 17:02 UTC, ValenberghsSven approved these changes

2023-10-20 17:02 UTC, merged